project:
  type: website
  output-dir: docs

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Blog
      - href: Projects.qmd
        text: Projects
      - href: Experience.qmd
        text: Experience


format:
  html:
    theme:
      - default
      - brand
    css: styles.css
