---
title: "Experience"
format: 
    html:
        code-fold: true
jupyter: python3
---
<br>

### Mac Lab Technician - Team Lead
##### BYU-Idaho - April 2025 - Present  
Support university projects and assisted students with technology and equipment needs.  
Responsibilities:  <div style = "margin-left: 20px">
  - Assisted the supervisor with decisions on lab policies and supported employees in daily tasks 
  - Contributed to university and Mac Lab projects by helping faculty print 3D models to improve teaching methods 
  - Managed 3D printers, checked out lab equipment, and communicated technical information for non-technical patrons 
</div>

Skills:  
```{=html}
<div class = "experience-stack">
    <div class = "experience-item">3d Printing</div>
    <div class = "experience-item">3d Modeling</div>
    <div class = "experience-item">Prusa Slicer</div>
    <div class = "experience-item">Employee leadership</div>
    <div class = "experience-item">Student Teaching</div>
</div>
```

<br>

### Maintenance Worker - McDonalds
##### May 2024 - September 2024
Maintained store equipment and building to ensure smooth daily operations. 
Responsibilities:  <div style = "margin-left: 20px">
  - Cleaned, maintained, and troubleshooted machinery  
  - Performed interior and exterior building maintenance; filtered fryers  
  - Managed inventory checks, cleaned dishes, and assisted with store closing duties  
</div>

Skills:  
```{=html}
<div class = "experience-stack">
    <div class = "experience-item">Machine Maintenance</div>
    <div class = "experience-item">Machine Troubleshooting</div>
    <div class = "experience-item">Inspect and Maintain building</div>
    <div class = "experience-item">Inventory Check</div>
</div>
```
<br><br><br>

::: {.text-center}
##### [Home](index.qmd)  |  [Projects](Projects.qmd)  |  [Blog](about.qmd)
:::

